bin/remarkable usr/bin/
remarkable.desktop usr/share/applications/

markdown/* usr/lib/python3/dist-packages/markdown/
remarkable_lib/* usr/lib/python3/dist-packages/remarkable_lib/
remarkable/* usr/lib/python3/dist-packages/remarkable/
pdfkit/* usr/lib/python3/dist-packages/pdfkit/

data/glib-2.0/schemas/* usr/share/glib-2.0/schemas/
data/media/* usr/share/remarkable/media/
data/ui/* usr/share/remarkable/ui/